export const AGENT_SIGNIN_REQUEST = "AGENT_SIGNIN_REQUEST";
export const AGENT_SIGNIN_SUCCESS = "AGENT_SIGNIN_SUCCESS";
export const AGENT_SIGNIN_FAIL = "AGENT_SIGNIN_FAIL";

export const AGENT_PROFILE_UPDATE_REQUEST = "AGENT_PROFILE_UPDATE_REQUEST";
export const AGENT_PROFILE_UPDATE_SUCCESS = "AGENT_PROFILE_UPDATE_SUCCESS";
export const AGENT_PROFILE_UPDATE_FAIL = "AGENT_PROFILE_UPDATE_FAIL";

export const AGENT_PROFILE_DETAILS_REQUEST = 'AGENT_PROFILE_DETAILS_REQUEST';
export const AGENT_PROFILE_DETAILS_SUCCESS = 'AGENT_PROFILE_DETAILS_SUCCESS';
export const AGENT_PROFILE_DETAILS_FAIL = 'AGENT_PROFILE_DETAILS_FAIL';

export const AGENT_PASSWORD_UPDATE_REQUEST = 'AGENT_PASSWORD_UPDATE_REQUEST';
export const AGENT_PASSWORD_UPDATE_SUCCESS = 'AGENT_PASSWORD_UPDATE_SUCCESS';
export const AGENT_PASSWORD_UPDATE_FAIL = 'AGENT_PASSWORD_UPDATE_FAIL';

export const AGENT_REGISTER_REQUEST = "AGENT_REGISTER_REQUEST";
export const AGENT_REGISTER_SUCCESS = "AGENT_REGISTER_SUCCESS";
export const AGENT_REGISTER_FAIL = "AGENT_REGISTER_FAIL";

export const AGENT_LOGOUT = "AGENT_LOGOUT";