export const AGENT_SIGNIN_REQUEST = "AGENT_SIGNIN_REQUEST";
export const AGENT_SIGNIN_SUCCESS = "AGENT_SIGNIN_SUCCESS";
export const AGENT_SIGNIN_FAIL = "AGENT_SIGNIN_FAIL";

export const AGENT_UPDATE_REQUEST = "AGENT_UPDATE_REQUEST";
export const AGENT_UPDATE_SUCCESS = "AGENT_UPDATE_SUCCESS";
export const AGENT_UPDATE_FAIL = "AGENT_UPDATE_FAIL";

export const AGENT_REGISTER_REQUEST = "AGENT_REGISTER_REQUEST";
export const AGENT_REGISTER_SUCCESS = "AGENT_REGISTER_SUCCESS";
export const AGENT_REGISTER_FAIL = "AGENT_REGISTER_FAIL";

export const AGENT_LOGOUT = "AGENT_LOGOUT";