export const APPSHARER_SIGNIN_REQUEST = 'APPSHARER_SIGNIN_REQUEST';
export const APPSHARER_SIGNIN_SUCCESS = 'APPSHARER_SIGNIN_SUCCESS';
export const APPSHARER_SIGNIN_FAIL = 'APPSHARER_SIGNIN_FAIL';

export const APPSHARER_UPDATE_REQUEST = 'APPSHARER_UPDATE_REQUEST';
export const APPSHARER_UPDATE_SUCCESS = 'APPSHARER_UPDATE_SUCCESS';
export const APPSHARER_UPDATE_FAIL = 'APPSHARER_UPDATE_FAIL';

export const APPSHARER_REGISTER_REQUEST = 'APPSHARER_REGISTER_REQUEST';
export const APPSHARER_REGISTER_SUCCESS = 'APPSHARER_REGISTER_SUCCESS';
export const APPSHARER_REGISTER_FAIL = 'APPSHARER_REGISTER_FAIL';

export const APPSHARER_LOGOUT = 'APPSHARER_LOGOUT';