export const WITHDRAW_LIST_REQUEST = "WITHDRAW_LIST_REQUEST"
export const WITHDRAW_LIST_SUCCESS = "WITHDRAW_LIST_SUCCESS"
export const WITHDRAW_LIST_FAIL = "WITHDRAW_LIST_FAIL"

export const WITHDRAW_LIST_REQUEST_AGENT = "WITHDRAW_LIST_REQUEST_AGENT"
export const WITHDRAW_LIST_SUCCESS_AGENT = "WITHDRAW_LIST_SUCCESS_AGENT"
export const WITHDRAW_LIST_FAIL_AGENT = "WITHDRAW_LIST_FAIL_AGENT"

export const WITHDRAW_LIST_REQUEST_APPSHARER = "WITHDRAW_LIST_REQUEST_APPSHARER"
export const WITHDRAW_LIST_SUCCESS_APPSHARER = "WITHDRAW_LIST_SUCCESS_APPSHARER"
export const WITHDRAW_LIST_FAIL_APPSHARER = "WITHDRAW_LIST_FAIL_APPSHARER"


export const WITHDRAW_LIST_REQUEST_KARROT = "WITHDRAW_LIST_REQUEST_KARROT"
export const WITHDRAW_LIST_SUCCESS_KARROT = "WITHDRAW_LIST_SUCCESS_KARROT"
export const WITHDRAW_LIST_FAIL_KARROT = "WITHDRAW_LIST_FAIL_KARROT"


export const WITHDRAW_LIST_REQUEST_CEO = "WITHDRAW_LIST_REQUEST_CEO"
export const WITHDRAW_LIST_SUCCESS_CEO = "WITHDRAW_LIST_SUCCESS_CEO"
export const WITHDRAW_LIST_FAIL_CEO = "WITHDRAW_LIST_FAIL_CEO"


export const WITHDRAW_REQUEST_APPSHARER = "WITHDRAW_REQUEST_APPSHARER"
export const WITHDRAW_SUCCESS_APPSHARER = "WITHDRAW_SUCCESS_APPSHARER"
export const WITHDRAW_FAIL_APPSHARER = "WITHDRAW_FAIL_APPSHARER"

export const WITHDRAW_REQUEST_AGENT = "WITHDRAW_REQUEST_AGENT"
export const WITHDRAW_SUCCESS_AGENT = "WITHDRAW_SUCCESS_AGENT"
export const WITHDRAW_FAIL_AGENT = "WITHDRAW_FAIL_AGENT"

export const WITHDRAW_REQUEST_KARROT = "WITHDRAW_REQUEST_KARROT"
export const WITHDRAW_SUCCESS_KARROT = "WITHDRAW_SUCCESS_KARROT"
export const WITHDRAW_FAIL_KARROT = "WITHDRAW_FAIL_KARROT"

export const WITHDRAW_REQUEST_CEO = "WITHDRAW_REQUEST_CEO"
export const WITHDRAW_SUCCESS_CEO = "WITHDRAW_SUCCESS_CEO"
export const WITHDRAW_FAIL_CEO = "WITHDRAW_FAIL_CEO"